create schema es;

create table es.phone_book(
    id integer primary key generated by default as identity,
    full_name varchar(64) not null,
    phone_number varchar(16) not null
);

create table es.task_manager(
    id integer primary key generated by default as identity,
    title varchar(32) not null,
    description varchar(256) not null,
    start_date timestamp not null,
    expiration_date timestamp not null
);